name = "aristotle"
version = "0.1.0"

lean_version = "leanprover/lean4:v4.20.0-rc5"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "d62eab0cc36ea522904895389c301cf8d844fd69"
