/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-/

/-
We define the group G generated by P and the set of edges E as the orbit of (a, b) under G. We prove that the graph defined by E is regular and vertex-transitive. We then show that if there are no edges between red vertices, the number of red vertices is at most the number of blue vertices, contradicting the majority coloring assumption. This implies the existence of an edge connecting two red vertices, proving the main result.
-/

import Mathlib.GroupTheory.GroupAction.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Rat.Defs
import Mathlib.Data.Set.Card

/-!
# Permutations and Pigeonhole Principle (Easy Version)

## Problem Statement

Let n ≥ 2 and let P be a set of permutations acting on [n] = {0, 1, 2, ..., n-1}.

**Assumptions:**
1. **Transitivity:** The set P acts transitively on [n], meaning that for any two elements
i, j ∈ [n], there exists a finite composition of permutations from P that maps i to j.
2. **Majority coloring:** More than half of the elements of [n] are colored red.

**Goal:** Show that for any two distinct elements a, b ∈ [n], there exists a finite composition
of permutations from P that simultaneously maps both a and b to red-colored positions.

## Main results

* `pppeasy`: Given a transitive set of permutations on a finite set with more than half
  the elements colored red, any pair of distinct elements can be moved by a composition of
  permutations to positions where both elements land on red.
-/

namespace PPPEasy
/--
  PROVIDED SOLUTION:
  Take any edge, and consider the graph consisting of all edges to which this edge can be moved.
  By transitivity, every vertex has the same degree, so the graph is regular.
  Consider the red vertices; since more than half of all vertices are red, there are many of them.
  If every edge starting from a red vertex ended at a blue vertex, then each blue vertex would receive more edges than any red vertex sends.
  This would contradict the regularity of the graph, because all vertices must have the same degree.
  Therefore, there must be an edge connecting two red vertices, which proves the claim.
-/
theorem pppeasy (n : ℕ) (hn : 2 ≤ n) (P : Set (Equiv.Perm (Fin n)))
    (h_trans : ∀ i j : Fin n, ∃ (σ : Equiv.Perm (Fin n)),
      (∃ (perms : List (Equiv.Perm (Fin n))), (∀ p ∈ perms, p ∈ P) ∧ σ = perms.foldl (· * ·) 1) ∧
      σ i = j)
    (red : Set (Fin n)) (h_red : (n : ℚ) / 2 < (red.ncard : ℚ))
    (a b : Fin n) (hab : a ≠ b) :
    ∃ (σ : Equiv.Perm (Fin n)),
      (∃ (perms : List (Equiv.Perm (Fin n))), (∀ p ∈ perms, p ∈ P) ∧ σ = perms.foldl (· * ·) 1) ∧
      σ a ∈ red ∧ σ b ∈ red := by
  sorry

end PPPEasy


/-
Define the group G generated by P, and the set of edges E as the orbit of (a, b) under G.
-/
def G (n : ℕ) (P : Set (Equiv.Perm (Fin n))) : Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure P

def E (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n) : Set (Fin n × Fin n) :=
  { x | ∃ σ ∈ G n P, x = (σ a, σ b) }

/-
The group G acts transitively on the set of vertices.
-/
lemma G_transitive (n : ℕ) (P : Set (Equiv.Perm (Fin n)))
    (h_trans : ∀ i j : Fin n, ∃ (σ : Equiv.Perm (Fin n)),
      (∃ (perms : List (Equiv.Perm (Fin n))), (∀ p ∈ perms, p ∈ P) ∧ σ = perms.foldl (· * ·) 1) ∧
      σ i = j) :
    MulAction.IsPretransitive (G n P) (Fin n) := by
      -- By definition of transitivity, we need to show that for any two elements i and j in Fin n, there exists a permutation σ in G such that σ i = j.
      have h_transitive : ∀ i j : Fin n, ∃ σ ∈ G n P, σ i = j := by
        intro i j; exact (by
        obtain ⟨ σ, ⟨ perms, hperms, rfl ⟩, hσ ⟩ := h_trans i j;
        use List.foldl (fun x1 x2 => x1 * x2) 1 perms;
        aesop;
        induction perms using List.reverseRecOn <;> aesop;
        exact Subgroup.mul_mem _ a_1 ( Subgroup.subset_closure ( hperms a ( Or.inr rfl ) ) ));
      exact ⟨ fun i j => by obtain ⟨ σ, hσ₁, hσ₂ ⟩ := h_transitive i j; exact ⟨ ⟨ σ, hσ₁ ⟩, hσ₂ ⟩ ⟩ ;

/-
The graph defined by E is regular, meaning every vertex has the same out-degree.
-/
def out_degree (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n) (v : Fin n) : ℕ :=
  { w | (v, w) ∈ E n P a b }.ncard

lemma graph_regular (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n)
    (h_trans : MulAction.IsPretransitive (G n P) (Fin n)) :
    ∀ v : Fin n, out_degree n P a b v = out_degree n P a b a := by
      -- By transitivity of the group action, for any vertex v, there exists a permutation σ in G such that σ(a) = v.
      have h_trans : ∀ v : Fin n, ∃ σ ∈ G n P, σ a = v := by
        exact fun v => by have := h_trans.exists_smul_eq a v; aesop;
      intros v
      obtain ⟨σ, hσG, hσa⟩ := h_trans v;
      unfold out_degree;
      rw [ show { w : Fin n | ( v, w ) ∈ E n P a b } = ( fun w => σ w ) '' { w : Fin n | ( a, w ) ∈ E n P a b } from ?_, Set.ncard_image_of_injective _ σ.injective ];
      -- To prove equality of sets, we show each set is a subset of the other.
      apply Set.ext
      intro w
      simp [Set.mem_image];
      -- By definition of $E$, we know that $(v, w) \in E n P a b$ if and only if there exists $\tau \in G n P$ such that $\tau a = v$ and $\tau b = w$.
      simp [E];
      constructor;
      · rintro ⟨ τ, hτG, rfl, rfl ⟩;
        refine' ⟨ σ⁻¹ * τ, _, _, _ ⟩ <;> simp_all +decide [ Subgroup.mul_mem_cancel_left, Subgroup.mul_mem_cancel_right ];
        · rw [ ← hσa, Equiv.Perm.inv_apply_self ];
        · rfl;
      · rintro ⟨ τ, hτG, hτa, hτb ⟩;
        exact ⟨ σ * τ, Subgroup.mul_mem _ hσG hτG, by simp +decide [ ← hσa, ← hτa ], by simp +decide [ ← hτb ] ⟩

/-
Define the in-degree of a vertex v as the number of edges ending at v.
-/
def in_degree (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n) (v : Fin n) : ℕ :=
  { u | (u, v) ∈ E n P a b }.ncard

/-
The in-degree is constant for all vertices in the graph defined by E.
-/
lemma in_degree_constant (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n)
    (h_trans : MulAction.IsPretransitive (G n P) (Fin n)) :
    ∀ v : Fin n, in_degree n P a b v = in_degree n P a b a := by
      intro v;
      -- Fix an arbitrary vertex $w$ and consider the set of edges ending at $w$. The number of such edges is equal to the number of edges starting at $v$ because $G$ acts transitively on $V$.
      obtain ⟨σ, hσ⟩ : ∃ σ ∈ G n P, v = σ a := by
        obtain ⟨ σ, hσ ⟩ := h_trans.exists_smul_eq a v; use σ; aesop;
      -- The set of edges ending at $v$ is $\{ (u, \sigma(a)) \mid \exists \tau \in G, \tau(a) = u, \tau(b) = \sigma(a) \}$.
      have h_edges_ending : {u : Fin n | (u, v) ∈ E n P a b} = {σ u | u ∈ {u : Fin n | (u, a) ∈ E n P a b}} := by
        ext u;
        -- If $(u, v) \in E n P a b$, then there exists $\sigma' \in G n P$ such that $u = \sigma' a$ and $v = \sigma' b$. Since $v = \sigma a$, we have $\sigma' b = \sigma a$. Thus, $\sigma' = \sigma \tau$ for some $\tau \in G n P$, and $\tau b = a$. Therefore, $u = \sigma (\tau a)$, which means $u$ is in the image of the set of edges ending at $a$ under $\sigma$.
        apply Iff.intro
        intro huv
        obtain ⟨σ', hσ', hu, hv⟩ : ∃ σ' ∈ G n P, u = σ' a ∧ v = σ' b := by
          cases huv ; aesop;
        · -- Since $σ' b = σ a$, we can write $σ' = σ * τ$ for some $τ \in G n P$.
          obtain ⟨τ, hτ⟩ : ∃ τ ∈ G n P, σ' = σ * τ := by
            exact ⟨ σ⁻¹ * σ', by exact Subgroup.mul_mem _ ( Subgroup.inv_mem _ hσ.1 ) hσ', by simp +decide ⟩;
          unfold E at *; aesop;
          exact ⟨ τ, left, rfl, rfl ⟩;
        · -- If there exists some $u'$ such that $(u', a) \in E n P a b$ and $\sigma u' = u$, then $(u, v) \in E n P a b$ because $\sigma * \tau \in G n P$ and $(\sigma * \tau) a = u$ and $(\sigma * \tau) b = v$.
          intro hu
          obtain ⟨u', hu', hu⟩ := hu
          obtain ⟨τ, hτ⟩ : ∃ τ ∈ G n P, u' = τ a ∧ a = τ b := by
            cases hu' ; aesop;
          use σ * τ;
          aesop;
      -- Since σ is a permutation, it is bijective, so the cardinality of the image is the same as the cardinality of the original set.
      have h_card_eq : Set.ncard {σ u | u ∈ {u | (u, a) ∈ E n P a b}} = Set.ncard {u | (u, a) ∈ E n P a b} := by
        -- Since σ is a permutation, it is a bijection, so the cardinality of the image is the same as the cardinality of the original set. Therefore, the two sets have the same cardinality.
        have h_card_eq : Set.ncard (Set.image σ {u | (u, a) ∈ E n P a b}) = Set.ncard {u | (u, a) ∈ E n P a b} := by
          rw [ Set.ncard_image_of_injective _ σ.injective ];
        convert h_card_eq using 1;
      unfold in_degree; aesop;

/-
The in-degree of every vertex is equal to its out-degree. This follows from the fact that the sum of in-degrees equals the sum of out-degrees (both equal the total number of edges), and both in-degree and out-degree are constant (independent of the vertex).
-/
lemma in_degree_eq_out_degree (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n)
    (h_trans : MulAction.IsPretransitive (G n P) (Fin n)) :
    ∀ v : Fin n, in_degree n P a b v = out_degree n P a b v := by
      -- Since the sum of in-degrees equals the sum of out-degrees, and both are constant, we can conclude that each in-degree equals the out-degree for every vertex.
      have h_sum_eq : ∑ v : Fin n, in_degree n P a b v = ∑ v : Fin n, out_degree n P a b v := by
        -- By definition of in-degree and out-degree, each edge contributes exactly once to the in-degree of its target vertex and once to the out-degree of its source vertex.
        have h_sum_eq : ∑ v : Fin n, in_degree n P a b v = ∑ v : Fin n, out_degree n P a b v := by
          have h_edges : ∀ σ ∈ G n P, (σ a, σ b) ∈ E n P a b := by
            exact fun σ hσ => ⟨ σ, hσ, rfl ⟩
          -- Let $R$ be the set of pairs $(u, v)$ such that $(u, v) \in E$.
          set R := { p : Fin n × Fin n | ∃ σ ∈ G n P, p = (σ a, σ b) };
          -- By definition of $R$, we can rewrite the sums in terms of $R$.
          have h_sum_eq : ∑ v : Fin n, in_degree n P a b v = ∑ v : Fin n, (R ∩ {p | p.2 = v}).ncard ∧ ∑ v : Fin n, out_degree n P a b v = ∑ v : Fin n, (R ∩ {p | p.1 = v}).ncard := by
            constructor <;> refine' Finset.sum_congr rfl fun v _ => _;
            · fapply Set.ncard_congr;
              use fun u hu => ( u, v );
              · aesop;
                rcases ha with ⟨ σ, hσ, rfl, rfl ⟩ ; exact ⟨ σ, hσ, rfl, rfl ⟩;
              · grind +ring;
              · grind;
            · fapply Set.ncard_congr;
              use fun w hw => ( v, w );
              · exact?;
              · aesop;
              · grind;
          rw [ h_sum_eq.1, h_sum_eq.2 ];
          -- Since $R$ is finite, we can apply the fact that the sum of the cardinalities of the intersections of $R$ with the sets $\{p | p.2 = v\}$ and $\{p | p.1 = v\}$ are equal.
          have h_finite : Set.Finite R := by
            exact Set.toFinite R;
          have h_sum_eq : ∑ v : Fin n, Finset.card (Finset.filter (fun p => p.2 = v) (h_finite.toFinset)) = ∑ v : Fin n, Finset.card (Finset.filter (fun p => p.1 = v) (h_finite.toFinset)) := by
            simp +decide only [Finset.card_filter];
            rw [ Finset.sum_comm ];
            simp +decide [ Finset.sum_ite ];
            rw [ ← Finset.card_biUnion ] ; congr ; ext ; aesop;
            exact fun x _ y _ hxy => Finset.disjoint_left.mpr fun z => by aesop;
          convert h_sum_eq using 2 <;> rw [ ← Set.ncard_coe_finset ] <;> aesop;
        exact?;
      -- Since the in-degree and out-degree are constant for all vertices, we can denote them as c_in and c_out respectively.
      obtain ⟨c_in, hc_in⟩ : ∃ c_in, ∀ v : Fin n, in_degree n P a b v = c_in := by
        exact ⟨ in_degree n P a b a, in_degree_constant n P a b h_trans ⟩
      obtain ⟨c_out, hc_out⟩ : ∃ c_out, ∀ v : Fin n, out_degree n P a b v = c_out := by
        exact ⟨ out_degree n P a b a, fun v => by simpa using graph_regular n P a b h_trans v ⟩;
      cases n <;> aesop;
      exact Fin.elim0 v

/-
The set of edges E is non-empty because it contains (a, b).
-/
lemma E_nonempty (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n) :
    (E n P a b).Nonempty := by
      -- Since the identity permutation is in G, we can take σ to be the identity, which gives us (a, b) in E.
      use (a, b)
      simp [E];
      exact ⟨ 1, Subgroup.one_mem _, rfl, rfl ⟩

/-
The degree of the graph is positive.
-/
lemma degree_pos (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n)
    (h_trans : MulAction.IsPretransitive (G n P) (Fin n)) :
    0 < out_degree n P a b a := by
      -- Since the identity permutation is in G, we have (a, b) ∈ E, which implies that the out-degree of a is at least 1.
      have h_identity : (a, b) ∈ E n P a b := by
        exact ⟨ 1, Subgroup.one_mem _, rfl ⟩;
      -- Since (a, b) is in E, the set {w | (a, w) ∈ E} is non-empty, which implies the out-degree is positive.
      have h_out_degree_pos : {w | (a, w) ∈ E n P a b}.Nonempty := by
        exact ⟨ b, h_identity ⟩;
      unfold out_degree;
      rw [ Set.ncard_pos ] ; aesop

/-
If there are no edges between two red vertices, then the number of red vertices is at most the number of blue vertices. This is because every edge starting from a red vertex must end at a blue vertex, and the graph is regular with positive degree.
-/
lemma card_red_le_card_blue (n : ℕ) (P : Set (Equiv.Perm (Fin n))) (a b : Fin n)
    (red : Set (Fin n))
    (h_trans : MulAction.IsPretransitive (G n P) (Fin n))
    (h_no_red_edge : ∀ (u v : Fin n), (u, v) ∈ E n P a b → ¬(u ∈ red ∧ v ∈ red)) :
    red.ncard ≤ (redᶜ).ncard := by
      -- Since $G$ acts transitively on $V$, the graph $E$ is regular with positive degree.
      obtain ⟨d, hd⟩ : ∃ d : ℕ, 0 < d ∧ ∀ v : Fin n, out_degree n P a b v = d := by
        exact ⟨ out_degree n P a b a, degree_pos n P a b h_trans, fun v => graph_regular n P a b h_trans v ⟩;
      -- Since there are no edges between red vertices, the total number of edges starting from red vertices is at most $d \cdot |\text{red}|$.
      have h_red_edges : (Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.1 ∈ red ∧ e.2 ∉ red}) ≥ d * Set.ncard red := by
        have h_red_edges : ∀ v ∈ red, Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.1 = v ∧ e.2 ∉ red} ≥ d := by
          intros v hv
          have h_red_edges : Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.1 = v} = d := by
            convert hd.2 v using 1;
            fapply Set.ncard_congr;
            use fun e he => e.2;
            · aesop;
            · aesop;
            · exact fun w hw => ⟨ ( v, w ), ⟨ hw, rfl ⟩, rfl ⟩;
          grind;
        have h_red_edges : ∀ s : Finset (Fin n), (∀ v ∈ s, v ∈ red) → Set.ncard (⋃ v ∈ s, {e : Fin n × Fin n | e ∈ E n P a b ∧ e.1 = v ∧ e.2 ∉ red}) ≥ d * s.card := by
          intros s hs;
          induction s using Finset.induction <;> aesop;
          rw [ @Set.ncard_union_eq ];
          · linarith [ h_red_edges a_1 left_1 ];
          · simp_all +decide [ Set.disjoint_left ];
          · exact Set.toFinite _;
          · exact Set.toFinite _;
        convert h_red_edges ( Set.Finite.toFinset ( show Set.Finite red from Set.toFinite red ) ) _;
        · aesop;
        · rw [ ← Set.ncard_coe_finset ] ; aesop;
        · aesop;
      -- Since there are no edges between red vertices, the total number of edges ending at blue vertices is at most $d \cdot |\text{blue}|$.
      have h_blue_edges : (Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 ∈ redᶜ ∧ e.1 ∈ red}) ≤ d * Set.ncard redᶜ := by
        -- For each blue vertex $v$, there are at most $d$ edges ending at $v$.
        have h_blue_edges_per_vertex : ∀ v ∈ redᶜ, (Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red}) ≤ d := by
          intros v hv
          have h_blue_edges_per_vertex : (Set.ncard {u : Fin n | (u, v) ∈ E n P a b ∧ u ∈ red}) ≤ d := by
            have h_blue_edges_per_vertex : (Set.ncard {u : Fin n | (u, v) ∈ E n P a b ∧ u ∈ red}) ≤ Set.ncard {u : Fin n | (u, v) ∈ E n P a b} := by
              apply_rules [ Set.ncard_le_ncard ];
              · aesop;
              · exact Set.toFinite _;
            have h_blue_edges_per_vertex : (Set.ncard {u : Fin n | (u, v) ∈ E n P a b}) = in_degree n P a b v := by
              exact?;
            have h_blue_edges_per_vertex : in_degree n P a b v = out_degree n P a b v := by
              exact?;
            linarith [ hd.2 v ];
          convert h_blue_edges_per_vertex using 1;
          fapply Set.ncard_congr;
          use fun e he => e.1;
          · grind;
          · aesop;
          · aesop;
        -- Summing over all blue vertices, the total number of edges ending at blue vertices is at most $d \cdot |\text{blue}|$.
        have h_blue_edges_total : (Set.ncard (⋃ v ∈ redᶜ, {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red})) ≤ d * Set.ncard redᶜ := by
          have h_blue_edges_total : (Set.ncard (⋃ v ∈ redᶜ, {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red})) ≤ ∑ v ∈ Set.Finite.toFinset (show Set.Finite redᶜ from Set.toFinite redᶜ), (Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red}) := by
                                                                                                                                                      have h_blue_edges_total : ∀ (s : Finset (Fin n)), (Set.ncard (⋃ v ∈ s, {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red})) ≤ ∑ v ∈ s, (Set.ncard {e : Fin n × Fin n | e ∈ E n P a b ∧ e.2 = v ∧ e.1 ∈ red}) := by
                                                                                                                                                        intros s; induction s using Finset.induction <;> aesop;
                                                                                                                                                        exact le_trans ( Set.ncard_union_le _ _ ) ( add_le_add_left a_3 _ );
                                                                                                                                                      convert h_blue_edges_total ( Set.Finite.toFinset ( show Set.Finite redᶜ from Set.toFinite redᶜ ) ) using 1;
                                                                                                                                                      congr!;
                                                                                                                                                      ext; simp [Set.mem_compl_iff];
          refine le_trans h_blue_edges_total ?_;
          refine' le_trans ( Finset.sum_le_sum fun v hv => h_blue_edges_per_vertex v <| by simpa using hv ) _ ; simp +decide [ mul_comm, Set.ncard_eq_toFinset_card' ];
          rw [ ← Set.ncard_coe_finset ] ; aesop;
        convert h_blue_edges_total using 2;
        ext; aesop;
      simp_all +decide [ Set.ncard_eq_toFinset_card' ];
      rw [ Set.inter_comm ] at h_blue_edges ; nlinarith

/-
Prove the main theorem pppeasy using the helper lemmas. Assume for contradiction that no edge connects two red vertices. Then by card_red_le_card_blue, the number of red vertices is at most the number of blue vertices, which contradicts the assumption that more than half the vertices are red. Therefore, there must be an edge connecting two red vertices, which corresponds to a permutation mapping a and b to red vertices.
-/
theorem pppeasy (n : ℕ) (hn : 2 ≤ n) (P : Set (Equiv.Perm (Fin n)))
    (h_trans : ∀ i j : Fin n, ∃ (σ : Equiv.Perm (Fin n)),
      (∃ (perms : List (Equiv.Perm (Fin n))), (∀ p ∈ perms, p ∈ P) ∧ σ = perms.foldl (· * ·) 1) ∧
      σ i = j)
    (red : Set (Fin n)) (h_red : (n : ℚ) / 2 < (red.ncard : ℚ))
    (a b : Fin n) (hab : a ≠ b) :
    ∃ (σ : Equiv.Perm (Fin n)),
      (∃ (perms : List (Equiv.Perm (Fin n))), (∀ p ∈ perms, p ∈ P) ∧ σ = perms.foldl (· * ·) 1) ∧
      σ a ∈ red ∧ σ b ∈ red := by
        convert PPPEasy.pppeasy n hn P h_trans red ( by
          convert h_red using 1 ) a b hab