import Mathlib
import Mathlib.Algebra.Lie.Weights.RootSystem
import Mathlib.LinearAlgebra.RootSystem.Finite.Lemmas

open LieAlgebra LieModule Module
variable {K L : Type*} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L] [FiniteDimensional K L]
variable {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
variable [IsKilling K L] [IsTriangularizable K H L]

lemma LieAlgebra.IsKilling.exists_coroot_pairing_ne_zero
    (β : Dual K H) (hβ : β ≠ 0) :
    ∃ i, (rootSystem H).toRootPairing.toLinearMap β ((rootSystem H).coroot i) ≠ 0 := by
      -- Assume for contradiction that for all roots i, β applied to the coroot of i is zero.
      by_contra h_contra
      have h_zero_on_span : ∀ x ∈ Submodule.span K (Set.range (rootSystem H).coroot), β x = 0 := by
        intro x hx; induction hx using Submodule.span_induction <;> aesop;
        rw [ ← right, h_contra _ left ];
      exact hβ ( by ext x; aesop )

lemma LieAlgebra.IsKilling.exists_root_mem_q_of_ne_bot
    (q : Submodule K (Dual K H))
    (hq : ∀ i, q ∈ End.invtSubmodule ((rootSystem H).reflection i))
    (h : q ≠ ⊥) :
    ∃ α ∈ H.root, ↑α ∈ q := by
      -- Since $q \neq \bot$, there exists $\beta \in q$ with $\beta \neq 0$.
      obtain ⟨β, hβ⟩ : ∃ β : Dual K H, β ∈ q ∧ β ≠ 0 := by
        exact ( Submodule.ne_bot_iff _ ).mp h;
      -- Since $q$ is invariant under the reflection corresponding to a root $\alpha_i$, we have $\alpha_i \in q$.
      obtain ⟨i, hi⟩ : ∃ i : H.root, (rootSystem H).toRootPairing.toLinearMap β ((rootSystem H).coroot i) ≠ 0 := by
        have := LieAlgebra.IsKilling.exists_coroot_pairing_ne_zero β;
        exact this hβ.2;
      -- Since $q$ is invariant under the reflection corresponding to $\alpha_i$, we have $\alpha_i \in q$.
      have h_alpha_i_in_q : (rootSystem H).toLinearMap β ((rootSystem H).coroot i) • (rootSystem H).root i ∈ q := by
        have h_alpha_i_in_q : (rootSystem H).reflection i β ∈ q := by
          -- Since $q$ is invariant under the reflection corresponding to $i$, we have $s_i(\beta) \in q$ by definition of invariance.
          apply hq i;
          exact hβ.1;
        -- Since $q$ is a submodule, subtracting $(β, α_i) * α_i$ from $β$ should keep it in $q$.
        have h_sub : β - ((rootSystem H).toLinearMap β ((rootSystem H).coroot i)) • (rootSystem H).root i ∈ q := by
          convert h_alpha_i_in_q using 1;
        simpa using q.sub_mem hβ.1 h_sub;
      use i.val; aesop;
      simpa [ smul_smul, hi ] using q.smul_mem ( β ( coroot val ) ) ⁻¹ h_alpha_i_in_q

lemma LieAlgebra.IsKilling.coroot_ne_zero
    {α : Weight K H L} (hα : α.IsNonZero) :
    coroot α ≠ 0 := by
      aesop

lemma LieAlgebra.IsKilling.sl2SubmoduleOfRoot_ne_bot
    {α : Weight K H L} (hα : α.IsNonZero) :
    sl2SubmoduleOfRoot hα ≠ ⊥ := by
      -- Since the coroot α is non-zero, the corootSubmodule α is not the zero submodule.
      have h_corootSubmodule_ne_bot : corootSubmodule α ≠ ⊥ := by
        simp_all +decide [ LieSubmodule.map, Submodule.eq_bot_iff ];
        obtain ⟨ x, hx ⟩ := ( show ∃ x : H, x ∈ corootSpace α ∧ x ≠ 0 from by
                                exact ⟨ coroot α, by simp +decide [ hα ], by simpa using coroot_ne_zero hα ⟩ ) ; use x, x ; aesop;
      -- Since the corootSubmodule α is non-zero, the sum of the three submodules (genWeightSpace L α, genWeightSpace L (-α), and corootSubmodule α) must also be non-zero.
      have h_sum_ne_bot : genWeightSpace L α ⊔ genWeightSpace L (-α) ⊔ corootSubmodule α ≠ ⊥ := by
        exact ne_bot_of_gt ( lt_of_lt_of_le ( lt_of_le_of_ne bot_le ( Ne.symm h_corootSubmodule_ne_bot ) ) ( le_sup_right ) );
      -- Since sl2SubmoduleOfRoot hα is defined as the sum of the three submodules, it follows directly that sl2SubmoduleOfRoot hα is also not the bottom submodule.
      convert h_sum_ne_bot using 1;
      exact?

lemma LieAlgebra.IsKilling.root_isNonZero (α : Weight K H L) (h : α ∈ H.root) : α.IsNonZero := by
  grind

lemma LieAlgebra.IsKilling.sl2SubmoduleOfRoot_le_invtSubmoduleToLieIdeal
    (q : Submodule K (Dual K H))
    (hq : ∀ i, q ∈ End.invtSubmodule ((rootSystem H).reflection i))
    {α : Weight K H L} (hα : α.IsNonZero) (hαq : ↑α ∈ q) :
    (sl2SubmoduleOfRoot hα).toSubmodule ≤ (invtSubmoduleToLieIdeal q hq).toSubmodule := by
      -- Since `sl2SubmoduleOfRoot hα` is one of the terms in the supremum, the submodule generated by it is contained in the supremum.
      have h_submodule : (sl2SubmoduleOfRoot hα).toSubmodule ≤ ⨆ α : {α : Weight K H L // ↑α ∈ q ∧ α.IsNonZero}, (sl2SubmoduleOfRoot α.2.2).toSubmodule := by
        exact le_iSup_of_le ⟨ α, hαq, hα ⟩ le_rfl
        all_goals unreachable!;
      convert h_submodule using 1;
      -- The ideal is defined as the supremum of the sl2SubmoduleOfRoot for all non-zero weights in q.
      simp [invtSubmoduleToLieIdeal]

lemma LieAlgebra.IsKilling.sl2SubmoduleOfRoot_toSubmodule_ne_bot
    {α : Weight K H L} (hα : α.IsNonZero) :
    (sl2SubmoduleOfRoot hα).toSubmodule ≠ ⊥ := by
      convert LieAlgebra.IsKilling.sl2SubmoduleOfRoot_ne_bot hα;
      -- The submodule of a Lie submodule is the same as the original submodule.
      simp [LieSubmodule.toSubmodule]

variable [IsSimple K L]

open Weight in
lemma LieAlgebra.IsKilling.l2 (q : Submodule K (Dual K H))
    (h₀ : ∀ (i : H.root), q ∈ End.invtSubmodule ((rootSystem H).reflection i))
    (h₁ : q ≠ ⊥) : q = ⊤ := by
  let J := (invtSubmoduleToLieIdeal q h₀)
  have r_j2 : J ≠ ⊥ := by
    sorry
  have : IsSimple K L := inferInstance
  have : J = ⊥ ∨ J = ⊤ := this.eq_bot_or_eq_top J
  have c₂ : J ≠ ⊥ := by
    exact r_j2
  have c₃ : J = ⊤ := by
    grind
  sorry
